### ISSUE TITLE
Pagination is in dark mode 

### ISSUE THREAD

**Issue by admirhusic** [admirhusic/GoodFirstIssueFinder#11]
The pagination seems to be in dark mode, even if we currently do not support dark mode. This should be fixed and the pagination should be white. 
<img width="949" alt="Screenshot 2024-07-01 at 23 20 21" src="https://github.com/admirhusic/GoodFirstIssueFinder/assets/16584154/fbf4ae37-265c-48a9-bbdc-6359d0bb0838">

**Comment by satyam1024** [comment]
Hello @admirhusic! Nice to meet you! I’m not sure if I’ll be able to fix it, but I would like to give it a try.

**Comment by admirhusic** [comment]
@satyam1024 The issue is yours! Good luck!

**Comment by satyam1024** [comment]
I am getting an error when running the app  can you help me with this 
![Uploading Screenshot (2845).png…]()

**Comment by admirhusic** [comment]
@satyam1024 have you configured the berear token in the .env file? If not, you have to go to developer settings in your Github account and activate a personal access token. Copy the env.example file a rename it to .env and set the token as the value. Hope this helps.

**Comment by satyam1024** [comment]
Thank you for your response. It seems that was indeed the issue. The feature is working now, but pagination isn't displaying in dark mode. Are there any specific conditions needed to replicate this problem?
![Screenshot (2846)](https://github.com/admirhusic/GoodFirstIssueFinder/assets/132131308/f7f783fd-64f7-4c8e-886c-1cb35a61294c)

**Comment by admirhusic** [comment]
@satyam1024 at the time of testing, it was night. I assume that tailwind has a way to detect the devices theme and set the background color. Not sure how this works.

**Comment by satyam1024** [comment]
then should we go ahead and close this issue now? or is there anything i can do.

**Comment by satyam1024** [comment]
This isn't related to the issue, but I want to thank you. When I first started contributing to open source, it was very overwhelming, and I was about to give up. Then I found your project and it really helped me a lot and I learned many things from it. Thank you

**Comment by admirhusic** [comment]
@satyam1024 You are welcome. I'm happy that this project motivated you. Keep on hacking!

**Comment by admirhusic** [comment]
@satyam1024 Let me know if you are working on this. If not, I will close this issue, since my idea is to implement a infinite scroll in the future, which will provide a better UX than the current implementation, and also the current pagination has some flaws.

**Comment by satyam1024** [comment]
No, please go ahead and close this issue.
