### ISSUE TITLE
Change the browser tab title from "React App" to "Good First Issue Finder"

### ISSUE THREAD

**Issue by admirhusic** [admirhusic/GoodFirstIssueFinder#12]
This is an ultra easy task, and the goal is to invite new developers to work on open source projects.

**Comment by aedoardo1990** [comment]
Hello @admirhusic! Nice to meet you! May I work this issue?

**Comment by satyam1024** [comment]
Hello @admirhusic! Nice to meet you! If it's not assigned, can I work on it?
