### ISSUE TITLE
Create loading component 

### ISSUE THREAD

**Issue by admirhusic** [admirhusic/GoodFirstIssueFinder#4]
The loading indicator while the list loads / api call is executed.

**Comment by admirhusic** [comment]
Currently there is a loading indicator, but there are problems sometimes with the animation. This should be solved in #9.

**Comment by aedoardo1990** [comment]
Hello @admirhusic,  may I work on this issue?

**Comment by admirhusic** [comment]
Hey, @aedoardo1990, thanks for your interest. Sure. It's yours.

**Comment by admirhusic** [comment]
Hello @aedoardo199, let me know if you are working on this.

**Comment by aedoardo1990** [comment]
Hello @admirhusic, I am sorry for my late reply. This weekend I am on a wedding, if it is fine for you I can work on it on Monday. If it has a high priority, feel free to assign it to someone else

**Comment by admirhusic** [comment]
@aedoardo1990 No worries, there is plenty of first good issues which you can take. For now, i will close the issue, since i made some refactorings and resloved the problem with the loader.
